apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sportif
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/part-of: sportif
    app: sportif

spec:
  project: default

  source:
    repoURL: https://github.com/churchlify/churchlify-gitops.git
    path: apps/sportif
    targetRevision: main

  destination:
    server: https://kubernetes.default.svc
    namespace: sports-tracking

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
