apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sports-tracking

resources:
  - ../../../shared/namespace.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app: api
  component: backend
  part-of: sportif
