apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sports-tracking

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

labels:
  - pairs:
      app: api
      component: backend
      part-of: sportif
