apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: sports-tracking

images:
- name: ghcr.io/agogos-llc/sportif-reel-worker
  newName: ghcr.io/agogos-llc/sportif-reel-worker
  newTag: sha-7e4d2b7
- name: ghcr.io/agogos-llc/sportif-stitch-worker
  newName: ghcr.io/agogos-llc/sportif-stitch-worker
  newTag: sha-7e4d2b7
- name: ghcr.io/agogos-llc/sportif/reel-worker
  newName: ghcr.io/agogos-llc/sportif/reel-worker
  newTag: sha-9fa09db
- name: ghcr.io/agogos-llc/sportif/sportif-reel-worker
  newName: ghcr.io/agogos-llc/sportif/sportif-reel-worker
  newTag: sha-94c5e23
- name: ghcr.io/agogos-llc/sportif/sportif-stitch-worker
  newName: ghcr.io/agogos-llc/sportif/sportif-stitch-worker
  newTag: sha-94c5e23
- name: ghcr.io/agogos-llc/sportif/stitch-worker
  newName: ghcr.io/agogos-llc/sportif/stitch-worker
  newTag: sha-9fa09db

labels:
- pairs:
    environment: production
