resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/agogos-llc/pigeons-api
  newName: ghcr.io/agogos-llc/pigeons-api
  newTag: cb75ed517b482b3a7850935086f7bf6eeb21fc7f
