resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/agogos-llc/pigeons-api
  newName: ghcr.io/agogos-llc/pigeons-api
  newTag: 9c8804933ba9755b6410d9a18f1bb37fad66ead4
