resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/agogos-llc/pigeons-api
  newName: ghcr.io/agogos-llc/pigeons-api
  newTag: 8ca4389536b5df4513b4371f911a7bba738a4802
