apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sports-tracking

resources:
  - deployment-stitch.yaml
  - deployment-reel.yaml
  - pvc-processing.yaml

labels:
  - pairs:
      app: processing-worker
      component: worker
      part-of: sportif
