apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sports-tracking

resources:
  - pvc-processing.yaml
  - deployment-stitch.yaml
  - deployment-reel.yaml

commonLabels:
  component: processing
  part-of: sportif
