apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: processing-temp
  namespace: sports-tracking
  labels:
    app: processing-worker
    component: processing
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Gi
