apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sports-tracking

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app: api-v2
  component: backend
  part-of: sportif-v2
