apiVersion: apps/v1
kind: Deployment
metadata:
  name: biblora-api
  namespace: biblora
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: biblora-api
  template:
    metadata:
      labels:
        app: biblora-api
    spec:
      initContainers:
        - name: db-init
          image: postgres:15
          command: ["sh", "-c"]
          args: |
            echo "Waiting for DB..."
            until pg_isready -h pgsql-postgresql.platform.svc.cluster.local -p 5432; do
              sleep 2
            done
            echo "DB is ready!"

        - name: prisma-migrate
          image: ghcr.io/churchlify/biblora-api:latest
          command: ["sh", "-c"]
          args:
            - |
              echo "Waiting for DB..."
              until nc -z pgsql-postgresql.platform.svc.cluster.local 5432; do
                sleep 3
              done
              echo "DB is ready!"
              echo "Running prisma migrations"
              npx prisma migrate deploy --schema ./prisma/schema.prisma
          envFrom:
            - secretRef:
                name: biblora-secrets

      containers:
        - name: api
          image: ghcr.io/churchlify/biblora-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NODE_OPTIONS
              value: "--dns-result-order=ipv4first"
          envFrom:
            - secretRef:
                name: biblora-secrets
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
