resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/agogos-llc/biblora-web
  newName: ghcr.io/agogos-llc/biblora-web
  newTag: 8d006f04d8dc2fef7e2c72df906d055e4d71f520
