resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/agogos-llc/biblora-web
  newName: ghcr.io/agogos-llc/biblora-web
  newTag: 5bb616f047bf5bb9c0b7c08d7cc5eb41e14a4bbb
