resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/agogos-llc/biblora-admin
  newName: ghcr.io/agogos-llc/biblora-admin
  newTag: ac69b1ac17aaf2f16b0bbff7005545fc478bda2d
- name: ghcr.io/agogos-llc/biblora-web
  newName: ghcr.io/agogos-llc/biblora-web
  newTag: 17cfc95eaa569238c7d4eca7b99270cf7a87e050
