resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/agogos-llc/biblora-admin
  newName: ghcr.io/agogos-llc/biblora-admin
  newTag: b2506a64ac974bf8abb784188375beae2cf7c95a
- name: ghcr.io/agogos-llc/biblora-web
  newName: ghcr.io/agogos-llc/biblora-web
  newTag: 17cfc95eaa569238c7d4eca7b99270cf7a87e050
