resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/agogos-llc/biblora-admin
  newName: ghcr.io/agogos-llc/biblora-admin
  newTag: 2af7853de4ddee0b0486611d7a8a09033ac3e12d
- name: ghcr.io/agogos-llc/biblora-web
  newName: ghcr.io/agogos-llc/biblora-web
  newTag: 17cfc95eaa569238c7d4eca7b99270cf7a87e050
