apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: sports-tracking

images:
- name: ghcr.io/agogos-llc/sportif-uploader-worker
  newName: ghcr.io/agogos-llc/sportif-uploader-worker
  newTag: sha-cdffcaf
- name: ghcr.io/agogos-llc/sportif/sportif-uploader-worker
  newName: ghcr.io/agogos-llc/sportif/sportif-uploader-worker
  newTag: sha-94c5e23
- name: ghcr.io/agogos-llc/sportif/uploader-worker
  newName: ghcr.io/agogos-llc/sportif/uploader-worker
  newTag: sha-9fa09db

labels:
- pairs:
    environment: production
