resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/churchlify/churchlify-api
  newName: ghcr.io/churchlify/churchlify-api
  newTag: d3c4a20f38cd6809c855a5e52d0325f603ebf697
