resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/churchlify/churchlify-pay
  newName: ghcr.io/churchlify/churchlify-pay
  newTag: bdac3eafad133a813f9675a3b3b24932f8e1c1e5
