apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: churchlify-api-files
  namespace: churchlify
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Adjust size as needed
  # storageClassName: standard # Only add if you have a specific storage class