apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sportif-secrets-sync
  namespace: sports-tracking
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: platform-secrets
    kind: ClusterSecretStore
  target:
    name: sportif-secrets
    creationPolicy: Merge
    template:
      engineVersion: v2
      mergePolicy: Merge
      data:
        IMMICH_API_KEY: "{{ .IMMICH_API_KEY }}"
        DATABASE_URL: "postgresql://{{ .PGSQL_USER }}:{{ .PGSQL_PASSWORD }}@{{ .PGSQL_HOST }}:5432/sportif_dev?schema=public&connection_limit=10&pool_timeout=30"
  data:
    - secretKey: IMMICH_API_KEY
      remoteRef:
        key: sportif-secrets
        property: IMMICH_API_KEY
    - secretKey: PGSQL_USER
      remoteRef:
        key: global-db-secrets
        property: PGSQL_USER
    - secretKey: PGSQL_PASSWORD
      remoteRef:
        key: global-db-secrets
        property: PGSQL_PASSWORD
    - secretKey: PGSQL_HOST
      remoteRef:
        key: global-db-secrets
        property: PGSQL_HOST
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sportif-api-secrets-sync
  namespace: sports-tracking
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: platform-secrets
    kind: ClusterSecretStore
  target:
    name: api-secrets
    creationPolicy: Merge
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: sportif-secrets
        property: JWT_SECRET
