apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: sports-tracking

images:
- name: ghcr.io/agogos-llc/sportif-notification-worker
  newName: ghcr.io/agogos-llc/sportif-notification-worker
  newTag: sha-f9ca117

labels:
- pairs:
    environment: production
