apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: sports-tracking

images:
  - name: ghcr.io/churchlify/sportif-notification-worker
    newTag: latest

labels:
  - pairs:
      environment: production
