apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agogos-platform-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: agogos-platform
    app.kubernetes.io/part-of: agogos
spec:
  project: default
  source:
    repoURL: https://github.com/churchlify/churchlify-gitops.git
    path: apps/agogos/platform/overlays/dev
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: agogos-dev
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
