resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/churchlify/churchlify-api
  newName: ghcr.io/churchlify/churchlify-api
  newTag: f397e15a72574cde0cd4e8f5538b26026d5b0ba7
