resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/churchlify/churchlify-api
  newName: ghcr.io/churchlify/churchlify-api
  newTag: 26b47b4439dc022edabbabf78d572cb960caed77
