resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/churchlify/churchlify-api
  newName: ghcr.io/churchlify/churchlify-api
  newTag: a5655e85ed8f0cd0b7d5e16ee921d795e9cc34df
