resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/agogos-llc/biblora-api
  newName: ghcr.io/agogos-llc/biblora-api
  newTag: a628f2d5e8b3e652453184c2c9a47bb9c18d467b
- name: ghcr.io/churchlify/biblora-api
  newName: ghcr.io/churchlify/biblora-api
  newTag: 95d549f8957ba5815363ee0de3d04fad41a5cfda
- name: ghcr.io/churchlify/churchlify/biblora-api
  newName: ghcr.io/churchlify/churchlify/biblora-api
  newTag: 28a1d2ea2284b7aa3deea3fa31cba1f6f01b002c
