resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/churchlify/churchlify/biblora-api
  newName: ghcr.io/churchlify/churchlify/biblora-api
  newTag: e743153f8108c650014b89748fdee4907e9592d1
