resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/churchlify/churchlify/biblora-api
  newName: ghcr.io/churchlify/churchlify/biblora-api
  newTag: 67a68bf8192907c19c6ad908fe6477ef24d9542d
