apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


namespace: sports-tracking

images:
- name: ghcr.io/agogos-llc/sportif-api
  newName: ghcr.io/agogos-llc/sportif-api
  newTag: sha-1406014
- name: ghcr.io/churchlify/sportif-api
  newTag: latest

replicas:
- count: 2
  name: api

commonLabels:
  environment: production
resources:
- ../../base
