apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: sports-tracking

images:
- name: ghcr.io/agogos-llc/sportif-api
  newName: ghcr.io/agogos-llc/sportif-api
  newTag: sha-a67e423
- name: ghcr.io/agogos-llc/sportif/api
  newName: ghcr.io/agogos-llc/sportif/api
  newTag: sha-94c5e23

replicas:
- count: 2
  name: api

labels:
- pairs:
    environment: production
