apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sportif-ml-storage-sync
  namespace: sportif-ml
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: platform-secrets
    kind: ClusterSecretStore
  target:
    name: sportif-ml-storage
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AWS_ACCESS_KEY_ID: "{{ .SPORTIF_ML_S3_ACCESS_KEY }}"
        AWS_SECRET_ACCESS_KEY: "{{ .SPORTIF_ML_S3_SECRET_KEY }}"
        CVAT_POSTGRES_HOST: "{{ .PGSQL_HOST }}"
        CVAT_POSTGRES_USER: "{{ .PGSQL_USER }}"
        CVAT_POSTGRES_PASSWORD: "{{ .PGSQL_PASSWORD }}"
        CVAT_REDIS_HOST: "{{ .REDIS_HOST }}"
  data:
    - secretKey: SPORTIF_ML_S3_ACCESS_KEY
      remoteRef:
        key: global-db-secrets
        property: SPORTIF_ML_S3_ACCESS_KEY
    - secretKey: SPORTIF_ML_S3_SECRET_KEY
      remoteRef:
        key: global-db-secrets
        property: SPORTIF_ML_S3_SECRET_KEY
    - secretKey: PGSQL_HOST
      remoteRef:
        key: global-db-secrets
        property: PGSQL_HOST
    - secretKey: PGSQL_USER
      remoteRef:
        key: global-db-secrets
        property: PGSQL_USER
    - secretKey: PGSQL_PASSWORD
      remoteRef:
        key: global-db-secrets
        property: PGSQL_PASSWORD
    - secretKey: REDIS_HOST
      remoteRef:
        key: global-db-secrets
        property: REDIS_HOST
