apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sportif-ml-storage-sync
  namespace: sportif-ml
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: platform-secrets
    kind: ClusterSecretStore
  target:
    name: sportif-ml-storage
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AWS_ACCESS_KEY_ID: "{{ .SPORTIF_ML_S3_ACCESS_KEY }}"
        AWS_SECRET_ACCESS_KEY: "{{ .SPORTIF_ML_S3_SECRET_KEY }}"
  data:
    - secretKey: SPORTIF_ML_S3_ACCESS_KEY
      remoteRef:
        key: global-db-secrets
        property: SPORTIF_ML_S3_ACCESS_KEY
    - secretKey: SPORTIF_ML_S3_SECRET_KEY
      remoteRef:
        key: global-db-secrets
        property: SPORTIF_ML_S3_SECRET_KEY
