apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sportif-ml-registry-sync
  namespace: sportif-ml
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: platform-secrets
    kind: ClusterSecretStore
  target:
    name: sportif-ml-registry
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .SPORTIF_ML_GHCR_CONFIG }}"
  data:
    - secretKey: SPORTIF_ML_GHCR_CONFIG
      remoteRef:
        key: global-db-secrets
        property: SPORTIF_ML_GHCR_CONFIG