apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api.yaml
  - configmap.yaml
  - registry-externalsecret.yaml
  - migration.yaml
  - service-accounts.yaml
  - web.yaml
  - worker.yaml
