apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api.yaml
  - configmap.yaml
  - database-bootstrap-externalsecret.yaml
  - database-bootstrap.yaml
  - disruption-budgets.yaml
  - registry-externalsecret.yaml
  - migration.yaml
  - runtime-externalsecret.yaml
  - service-accounts.yaml
  - web.yaml
  - worker.yaml
