apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: agogos-platform-registry-sync
  annotations:
    argocd.argoproj.io/sync-wave: '-2'
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: platform-secrets
    kind: ClusterSecretStore
  target:
    name: agogos-platform-registry
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .AGOGOS_GHCR_CONFIG }}"
  data:
    - secretKey: AGOGOS_GHCR_CONFIG
      remoteRef:
        key: global-db-secrets
        property: SPORTIF_ML_GHCR_CONFIG