apiVersion: v1
kind: ServiceAccount
metadata:
  name: agogos-api
  annotations:
    argocd.argoproj.io/sync-wave: '-2'
automountServiceAccountToken: false
imagePullSecrets:
  - name: agogos-platform-registry
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: agogos-migration
  annotations:
    argocd.argoproj.io/sync-wave: '-2'
automountServiceAccountToken: false
imagePullSecrets:
  - name: agogos-platform-registry
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: agogos-web
  annotations:
    argocd.argoproj.io/sync-wave: '-2'
automountServiceAccountToken: false
imagePullSecrets:
  - name: agogos-platform-registry
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: agogos-worker
  annotations:
    argocd.argoproj.io/sync-wave: '-2'
automountServiceAccountToken: false
imagePullSecrets:
  - name: agogos-platform-registry
