resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/agogos-llc/agogos-web
  newName: ghcr.io/agogos-llc/agogos-web
  newTag: 65a52c8757741c6206f865c8efa063297510c380
