resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/agogos-llc/agogos-web
  newName: ghcr.io/agogos-llc/agogos-web
  newTag: 5ae0375edc923135447e284884857b7e0a29b049
