resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/agogos-llc/agogos-web
  newName: ghcr.io/agogos-llc/agogos-web
  newTag: cf22b527ed13e98b19908adb9fe9d201addf52c2
