resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/agogos-llc/churchlify-api-v2
  newName: ghcr.io/agogos-llc/churchlify-api-v2
  newTag: 87df44da4a935743b394d15df1fd723c98c93551
