resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/agogos-llc/churchlify-api-v2
  newName: ghcr.io/agogos-llc/churchlify-api-v2
  newTag: e00492339b4eeb2b4027137a2c96c92b0d4e2639
