resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/agogos-llc/churchlify-api-v2
  newName: ghcr.io/agogos-llc/churchlify-api-v2
  newTag: 24e6ad31d07d02750b758956c45ce8e88613b376
