apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sports-tracking

resources:
  - ../../../shared/namespace.yaml
  - deployment-tracking.yaml

commonLabels:
  app: tracking-worker
  component: tracking
  part-of: sportif
