apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailu-antivirus
  namespace: mailu
spec:
  selector:
    matchLabels:
      app: mailu-antivirus
  template:
    metadata:
      labels:
        app: mailu-antivirus
    spec:
      containers:
      - name: antivirus
        image: ghcr.io/mailu/clamav:2024.06
        envFrom:
        - configMapRef:
            name: mailu-config
        - secretRef:
            name: mailu-secrets
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "2Gi"
        volumeMounts:
        - name: clamav-data
          mountPath: /var/lib/clamav
        - name: clamav-run
          mountPath: /var/run/clamav
      volumes:
      - name: clamav-data
        persistentVolumeClaim:
          claimName: mailu-clamav-pvc
      - name: clamav-run
        emptyDir: {}