apiVersion: v1
kind: ConfigMap
metadata:
  name: mailu-config
  namespace: mailu
data:
  
  # Ensure these are still here to keep 'front' happy
  DOMAIN: "churchlify.com"
  HOSTNAMES: "mail.churchlify.com,mailadmin.churchlify.com"
  HOSTNAME: "mail.churchlify.com"
  
  TLS_FLAVOR: "notls"
  
  WEBROOT: "/"
  WEB_ADMIN: "/admin"
  SITENAME: "Churchlify Mail"
  
  ADMIN_ADDRESS: "mailu-admin"
  IMAP_ADDRESS: "mailu-dovecot"
  ANTISPAM_ADDRESS: "mailu-rspamd"
  SMTP_ADDRESS: "mailu-smtp"
  REDIS_ADDRESS: "redis.platform.svc.cluster.local"

  WEBMAIL_ADDRESS: "localhost"
  API_ADDRESS: "localhost"
  WELCOME_ADDRESS: "localhost"
  
  # --- Network & SSL ---
  REAL_IP_HEADER: "X-Forwarded-For"
  REAL_IP_FROM: "10.0.0.0/8,192.168.0.0/16,172.16.0.0/12" # Trust internal K8s IPs
  
  
  RELAYHOST: "smtp-relay.brevo.com"
  RELAYPORT: "587"
  RELAYNETS: "0.0.0.0/0"
  OUTBOUND_TLS_LEVEL: "encrypt"
  
  AUTH_RATELIMIT: "10/minute;100/hour"
  DKIM_SELECTOR: "mailu"
  MESSAGE_SIZE_LIMIT: "52428800"