apiVersion: v1
kind: Namespace
metadata:
  name: mailu
---
apiVersion: v1
kind: Secret
metadata:
  name: mailu-secrets
  namespace: mailu
type: Opaque
stringData:
  SECRET_KEY: EQDBJFW1BF8GQH94
  API_TOKEN: F917B38H162PRYTXSIGC0R9XTK02PKP7
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mailu-config
  namespace: mailu
data:
  DOMAIN: "mail.churchlify.com"
  HOSTNAMES: "mail.churchlify.com"
  SITENAME: "Churchlify Mail"

  TLS_FLAVOR: "letsencrypt"
  LETSENCRYPT_EMAIL: "admin@churchlify.com"

  SECRET_KEY: "change-me"

  REDIS_ADDRESS: "redis.mailu.svc.cluster.local"

  WEBMAIL: "roundcube"
  WEBDAV: "radicale"
  ANTIVIRUS: "clamav"

  MESSAGE_SIZE_LIMIT: "50000000"

  WELCOME: "false"
  ADMIN: "true"

  LOG_LEVEL: "INFO"
  TZ: "Etc/UTC"

  WEBROOT_REDIRECT: "/webmail"
  WEB_ADMIN: "/admin"
  WEB_WEBMAIL: "/webmail"
  WEB_API: "/api"

  REJECT_UNLISTED_RECIPIENT: "yes"