apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailu-admin
  namespace: mailu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailu-admin
  template:
    metadata:
      labels:
        app: mailu-admin
    spec:
      serviceAccountName: mailu-admin-sa
      # Ensure the token is actually injected for Socrate to find
      automountServiceAccountToken: true 
      containers:
        - name: admin
          image: ghcr.io/mailu/admin:2024.06.49
          securityContext:
            runAsUser: 0
            capabilities:
              add: ["NET_ADMIN"] # Fixed indentation here
          envFrom:
            - configMapRef:
                name: mailu-config
            - secretRef:
                name: mailu-secret
          ports:
            - containerPort: 80
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mailu-data-pvc