apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - clamav.yaml
  - configns.yaml
  - deployment.yaml
  - postfix.yaml
  - pvc.yaml
  - roundcube.yaml
  - rspamd.yaml
  - services.yaml
  - service_ingress.yaml
  - unbound.yaml
  - webdav.yaml