apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/instance: churchlify-mail
  app.kubernetes.io/part-of: mailu
resources:
  - pvc_db.yaml
  - pvc_mail.yaml
  - pvc_rspamd.yaml
  - config.yaml
  - secrets.yaml
  - service_admin.yaml
  - service_dovecot.yaml
  - service_rspamd.yaml
  - service.yaml
  - deployment_admin.yaml
  - deployment_dovecot.yaml
  - deployment_postfix.yaml
  - deployment_rspamd.yaml
  - ingress.yaml