apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mailu-rspamd-storage
  namespace: mailu
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi