apiVersion: v1
kind: Secret
metadata:
  name: mailu-secret
  namespace: mailu
type: Opaque
stringData:
  SECRET_KEY: "iG815234crLsY0De59IucwGF" 
---
apiVersion: v1
kind: Secret
metadata:
  name: brevo-smtp
  namespace: mailu
type: Opaque
stringData:
  RELAY_USER: "a6b770001@smtp-brevo.com"