apiVersion: v1
kind: Service
metadata:
  name: admin
  namespace: mailu
spec:
  ports:
  - name: admin
    port: 80
    targetPort: 80
  selector:
    app: admin
---
apiVersion: v1
kind: Service
metadata:
  name: imap
  namespace: mailu
spec:
  ports:
    - name: imap
      port: 143
      targetPort: 143
    - name: imaps
      port: 993
      targetPort: 993
    - name: sieve
      port: 4190
      targetPort: 4190
  selector:
    app: imap
---
apiVersion: v1
kind: Service
metadata:
  name: smtp
  namespace: mailu
spec:
  ports:
    - name: smtp
      port: 25
      targetPort: 25
    - name: smtps
      port: 465
      targetPort: 465
    - name: submission
      port: 587
      targetPort: 587
  selector:
    app: mailu-smtp
---
apiVersion: v1
kind: Service
metadata:
  name: antispam
  namespace: mailu
spec:
  ports:
    - name: rspamd
      port: 11332
      targetPort: 11332
    - name: rspamd-controller
      port: 11334
      targetPort: 11334
  selector:
    app: mailu-antispam
---
apiVersion: v1
kind: Service
metadata:
  name: antivirus
  namespace: mailu
spec:
  ports:
    - name: clamd
      port: 3310
      targetPort: 3310
  selector:
    app: mailu-antivirus
---
apiVersion: v1
kind: Service
metadata:
  name: webmail
  namespace: mailu
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: mailu-webmail
---
apiVersion: v1
kind: Service
metadata:
  name: front
  namespace: mailu
spec:
  selector:
    app: mailu-front
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
