apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailu-resolver
  namespace: mailu
spec:
  selector:
    matchLabels:
      app: mailu-resolver
  template:
    metadata:
      labels:
        app: mailu-resolver
    spec:
      containers:
      - name: resolver
        image: ghcr.io/mailu/unbound:2024.06
        envFrom:
        - configMapRef:
            name: mailu-config
        - secretRef:
            name: mailu-secrets
        ports:
        - containerPort: 53
          protocol: UDP
        - containerPort: 53
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 53
          initialDelaySeconds: 10
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: resolver
  namespace: mailu
spec:
  ports:
  - name: dns-udp
    port: 53
    protocol: UDP
    targetPort: 53
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
  selector:
    app: mailu-resolver