apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - service_ingress.yaml

# Use this section to override the Redis address for production if needed
configMapGenerator:
- name: mailu-config
  behavior: merge
  literals:
  - REDIS_ADDRESS=redis.platform.svc.cluster.local