apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cvat-postgres-sync
  namespace: sportif-ml
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: platform-secrets
    kind: ClusterSecretStore
  target:
    name: cvat-postgres-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        database: "cvat"
        username: "{{ .CVAT_PGSQL_USER }}"
        password: "{{ .CVAT_PGSQL_PASSWORD }}"
  data:
    - secretKey: CVAT_PGSQL_USER
      remoteRef:
        key: global-db-secrets
        property: CVAT_PGSQL_USER
    - secretKey: CVAT_PGSQL_PASSWORD
      remoteRef:
        key: global-db-secrets
        property: CVAT_PGSQL_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cvat-redis-sync
  namespace: sportif-ml
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: platform-secrets
    kind: ClusterSecretStore
  target:
    name: cvat-redis-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        password: "{{ .REDIS_PASSWORD }}"
  data:
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: global-db-secrets
        property: REDIS_PASSWORD
