apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sports-tracking

resources:
  - ../../../shared/namespace.yaml
  - deployment-recorder.yaml
  - deployment-media-ingest.yaml
  - configmap-srs.yaml
  - configmap-mediamtx.yaml
  - pvc-recorder.yaml
  - rbac-recorder.yaml

commonLabels:
  app: recorder-worker
  component: media-ingest
  part-of: sportif
