apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recorder-segments-pvc
  namespace: sports-tracking
  labels:
    app: recorder-worker
    chunk: c06-ingest
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 500Gi
