apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


namespace: sports-tracking

images:
- name: ghcr.io/agogos-llc/sportif-preview-worker
  newName: ghcr.io/agogos-llc/sportif-preview-worker
  newTag: sha-3540612
- name: ghcr.io/churchlify/sportif-preview-worker
  newTag: latest

replicas:
- count: 1
  name: preview-streamer

commonLabels:
  environment: production
resources:
- ../../base
