apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: sports-tracking

images:
  - name: ghcr.io/churchlify/sportif-preview-worker
    newTag: latest

replicas:
  - name: preview-streamer
    count: 1

commonLabels:
  environment: production
