apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coturn
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/churchlify/churchlify-gitops.git'
    targetRevision: HEAD
    path: platform/coturn
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true