apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sportif
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    repoURL: https://github.com/agogos-llc/app-ops
    targetRevision: main
    path: apps/sportif

  destination:
    server: https://kubernetes.default.svc
    namespace: sports-tracking

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false # Namespace is shared with sport-track
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
