resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/agogos-llc/churchlify-api-v3
  newName: ghcr.io/agogos-llc/churchlify-api-v3
  newTag: c2fcd74ba99f02ed5e39767077e8e832a4487a5b
