resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/agogos-llc/churchlify-api-v3
  newName: ghcr.io/agogos-llc/churchlify-api-v3
  newTag: 9cad0c619feabd7ea539ed4d3d2f6d5ce0f7eb87
