apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: coturn-secret-sync
  namespace: platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: platform-secrets
    kind: ClusterSecretStore
  target:
    name: coturn-secrets
    creationPolicy: Owner
  data:
    - secretKey: TURN_SECRET
      remoteRef:
        key: global-db-secrets
        property: TURN_SECRET
