apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sports-tracking

resources:
  - deployment-preview-streamer.yaml
  - deployment-preview-worker.yaml
  - configmap-srs.yaml
  - configmap-mediamtx.yaml

commonLabels:
  app: preview-worker
  component: preview
  part-of: sportif
