apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sports-media-pvc-rwx
  namespace: sports-tracking
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Gi
