apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: sports-tracking-staging

images:
  - name: ghcr.io/agogos-llc/sportif-api
    newTag: latest

replicas:
  - name: api
    count: 1

commonLabels:
  environment: staging
