apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sports-tracking-staging

bases:
  - ../../base

replicas:
  - name: cleanup-worker
    count: 1

images:
  - name: ghcr.io/agogos-llc/sportif-cleanup-worker
    newTag: latest

commonLabels:
  environment: staging
