apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: sports-tracking-staging

images:
  - name: ghcr.io/churchlify/sportif-stitch-worker
    newTag: latest
  - name: ghcr.io/churchlify/sportif-reel-worker
    newTag: latest

replicas:
  - name: stitch-worker
    count: 1
  - name: reel-worker
    count: 1

commonLabels:
  environment: staging
