apiVersion: apps/v1
kind: Deployment
metadata:
  name: live-stitcher
  namespace: sports-tracking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: live-stitcher
  template:
    metadata:
      labels:
        app: live-stitcher
    spec:
      containers:
        - name: live-engine
          image: ghcr.io/agogos-llc/sport-track-stitch-v2:latest
          imagePullPolicy: IfNotPresent
          command:
            - python
            - /app/post_stitcher.py
          args:
            - --left
            - $(LEFT_CAMERA_URL)
            - --right
            - $(RIGHT_CAMERA_URL)
            - --output
            - $(PREVIEW_RTSP_URL)
          env:
            - name: LEFT_CAMERA_URL
              value: rtsp://preview-streamer-service.sports-tracking.svc.cluster.local:8554/left
            - name: RIGHT_CAMERA_URL
              value: rtsp://preview-streamer-service.sports-tracking.svc.cluster.local:8554/right
            - name: PREVIEW_RTSP_URL
              value: rtsp://preview-streamer-service.sports-tracking.svc.cluster.local:8554/stitched_preview
            - name: AI_TRACKER_URL
              value: http://sport-track-service.sports-tracking.svc.cluster.local:8000/crop-x
          volumeMounts:
            - mountPath: /var/recordings
              name: media-storage
              subPath: recordings
      volumes:
        - name: media-storage
          persistentVolumeClaim:
            claimName: sports-media-pvc
