resources:
  # - deployment-sport-track.yaml
  # - deployment-live-stitcher.yaml
  # - deployment-reel-generator.yaml # <--- Added API Service Deployment
  - service.yaml
  - service-ai.yaml
  - ingress.yaml
  - nginx-patch.yaml
