apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sports-media-pvc
  namespace: sports-tracking
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-nvme
  resources:
    requests:
      storage: 50Gi
