apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sports-media-pvc
  namespace: sports-tracking
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-nvme # Update this to match your exact NVMe StorageClass name
  resources:
    requests:
      storage: 50Gi
