apiVersion: v1
kind: Service
metadata:
  name: media-ingest-service
  namespace: sports-tracking
spec:
  type: LoadBalancer
  selector:
    app: media-ingest
  ports:
    - name: rtmp
      protocol: TCP
      port: 1935
      targetPort: 1935
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
