apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: sports-tracking

images:
- name: ghcr.io/agogos-llc/sportif-cleanup-worker
  newName: ghcr.io/agogos-llc/sportif-cleanup-worker
  newTag: sha-f2397f8
- name: ghcr.io/agogos-llc/sportif/cleanup-worker
  newName: ghcr.io/agogos-llc/sportif/cleanup-worker
  newTag: sha-9fa09db
- name: ghcr.io/agogos-llc/sportif/sportif-cleanup-worker
  newName: ghcr.io/agogos-llc/sportif/sportif-cleanup-worker
  newTag: sha-94c5e23

labels:
- pairs:
    environment: production
