resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/agogos-llc/biblora-pay
  newName: ghcr.io/agogos-llc/biblora-pay
  newTag: 3d49d711685dfcef05e54ecb70e730f50889c90c
- name: ghcr.io/churchlify/biblora-pay
  newName: ghcr.io/churchlify/biblora-pay
  newTag: dae45e22bbe252750f67238de64209caf7c18e41
