apiVersion: apps/v1
kind: Deployment
metadata:
  name: agogos-api
spec:
  template:
    spec:
      containers:
        - name: api
          envFrom:
            - configMapRef:
                name: agogos-platform-config
            - secretRef:
                name: agogos-platform-runtime
            - secretRef:
                name: agogos-platform-email