apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: agogos-platform-email
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: platform-secrets
  target:
    name: agogos-platform-email
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      type: Opaque
      metadata:
        annotations:
          argocd.argoproj.io/sync-wave: "-2"
  data:
    - secretKey: EMAIL_FROM
      remoteRef: { key: global-db-secrets, property: EMAIL_FROM }
    - secretKey: EMAIL_REPLY_TO
      remoteRef: { key: global-db-secrets, property: EMAIL_REPLY_TO }
    - secretKey: RESEND_API_KEY
      remoteRef: { key: global-db-secrets, property: RESEND_API_KEY }
    - secretKey: BREVO_API_KEY
      remoteRef: { key: global-db-secrets, property: BREVO_API_KEY }
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef: { key: global-db-secrets, property: AWS_ACCESS_KEY_ID }
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef: { key: global-db-secrets, property: AWS_SECRET_ACCESS_KEY }
    - secretKey: AWS_SESSION_TOKEN
      remoteRef: { key: global-db-secrets, property: AWS_SESSION_TOKEN }