apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: agogos-dev

resources:
  - ../../base
  - ingress.yaml
  - network-policies.yaml
  - namespace.yaml
  - postgres.yaml
  - redis.yaml

patches:
  - path: api-config-revision.patch.yaml
  - path: delete-database-bootstrap-externalsecret.patch.yaml
  - path: delete-database-bootstrap.patch.yaml
  - path: delete-runtime-externalsecret.patch.yaml
  - path: platform-config.patch.yaml

secretGenerator:
  - name: agogos-platform-runtime
    literals:
      - DATABASE_URL=postgresql://agogos:agogos-dev-only@agogos-postgres:5432/agogos
      - BILLING_WEBHOOK_SECRET=local-development-billing-secret-32
      - CONNECTOR_CREDENTIAL_ENCRYPTION_KEY=bG9jYWwtZGV2ZWxvcG1lbnQtZW5jcnlwdGlvbi1rZXk
      - POSTGRES_DB=agogos
      - POSTGRES_PASSWORD=agogos-dev-only
      - POSTGRES_USER=agogos
      - REDIS_URL=redis://agogos-redis:6379

generatorOptions:
  disableNameSuffixHash: true
  annotations:
    argocd.argoproj.io/sync-wave: "-2"

images:
  - name: ghcr.io/agogos-llc/agogos-platform-api
    newName: ghcr.io/agogos-llc/agogos-platform-api
    digest: sha256:56cecf28a179ffeb46f5c6ca41757ada00f309eda1e39ea09f3ebd812a0afd4f
  - name: ghcr.io/agogos-llc/agogos-platform-migration
    newName: ghcr.io/agogos-llc/agogos-platform-migration
    digest: sha256:e15f1b5c4307419d8d5a123b3c6b4b3c706c15d2fd5f8a2f957dba8aa467bc8f
  - name: ghcr.io/agogos-llc/agogos-platform-web
    newName: ghcr.io/agogos-llc/agogos-platform-web
    digest: sha256:df034d9d3e841e1dbc1077739aec8c1e0101427b0d7ee55eb4d32354226a93aa
  - name: ghcr.io/agogos-llc/agogos-platform-worker
    newName: ghcr.io/agogos-llc/agogos-platform-worker
    digest: sha256:254a6a0e71fce2486d47ed93b14512b512a836b70ca63ff776dbf30623b30700
