apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: agogos-dev

resources:
  - ../../base
  - ingress.yaml
  - network-policies.yaml
  - namespace.yaml
  - postgres.yaml
  - redis.yaml

patches:
  - path: api-config-revision.patch.yaml
  - path: delete-database-bootstrap-externalsecret.patch.yaml
  - path: delete-database-bootstrap.patch.yaml
  - path: delete-runtime-externalsecret.patch.yaml
  - path: platform-config.patch.yaml

secretGenerator:
  - name: agogos-platform-runtime
    literals:
      - DATABASE_URL=postgresql://agogos:agogos-dev-only@agogos-postgres:5432/agogos
      - BILLING_WEBHOOK_SECRET=local-development-billing-secret-32
      - CONNECTOR_CREDENTIAL_ENCRYPTION_KEY=bG9jYWwtZGV2ZWxvcG1lbnQtZW5jcnlwdGlvbi1rZXk
      - POSTGRES_DB=agogos
      - POSTGRES_PASSWORD=agogos-dev-only
      - POSTGRES_USER=agogos
      - REDIS_URL=redis://agogos-redis:6379

generatorOptions:
  disableNameSuffixHash: true
  annotations:
    argocd.argoproj.io/sync-wave: "-2"

images:
  - name: ghcr.io/agogos-llc/agogos-platform-api
    newName: ghcr.io/agogos-llc/agogos-platform-api
    digest: sha256:d1580f4ea6b5ab588ea07227a83bc89da8a246fb3d9d70e1eade9c618384d8c1
  - name: ghcr.io/agogos-llc/agogos-platform-migration
    newName: ghcr.io/agogos-llc/agogos-platform-migration
    digest: sha256:4fe281d15bf02e2dbf1fb723ed0fb756aefd3c5595b73204d3f13a9b2221af64
  - name: ghcr.io/agogos-llc/agogos-platform-web
    newName: ghcr.io/agogos-llc/agogos-platform-web
    digest: sha256:43ba1dc1c2214c053fba7fb728d1e861777613a8a5e59f9316c91c2350ea627b
  - name: ghcr.io/agogos-llc/agogos-platform-worker
    newName: ghcr.io/agogos-llc/agogos-platform-worker
    digest: sha256:4202059098c3999854374adc5cb4db3dd126b642e43bba7f6ae00666980e1028
