apiVersion: v1
kind: ConfigMap
metadata:
  name: agogos-platform-config
data:
  API_CORS_ORIGIN: https://dev.agogos.org
  APP_ENV: dev
  BILLING_PROVIDER: stripe
  BILLING_RETURN_URL_ORIGINS: https://dev.agogos.org
  BILLING_SUPPORTED_CURRENCIES: USD,NGN,GHS,ZAR,KES,UGX,TZS
  BUILD_SHA: 641074edf320b7ff87faecf833d6ac02f95876ec
  BUILD_VERSION: 0.0.0-641074edf320b7ff87faecf833d6ac02f95876ec
  EMAIL_PROVIDER: resend
  INTERNAL_EMAIL_DOMAINS: agogos.org
  IAM_HIGH_RISK_APPROVER_ROLES: SECURITY_ADMIN,SUPER_ADMIN
  LOG_LEVEL: info
  PORTAL_BASE_URL: https://dev.agogos.org
