apiVersion: v1
kind: ConfigMap
metadata:
  name: agogos-platform-config
data:
  API_CORS_ORIGIN: https://dev.agogos.org
  APP_ENV: dev
  BILLING_PROVIDER: stripe
  BILLING_RETURN_URL_ORIGINS: https://dev.agogos.org
  BILLING_SUPPORTED_CURRENCIES: USD,NGN,GHS,ZAR,KES,UGX,TZS
  BUILD_SHA: cb30cf0e5cb55fdf0e7ef0c551519a6a95599efa
  BUILD_VERSION: 0.0.0-cb30cf0e5cb55fdf0e7ef0c551519a6a95599efa
  EMAIL_PROVIDER: resend
  INTERNAL_EMAIL_DOMAINS: agogos.org
  IAM_HIGH_RISK_APPROVER_ROLES: SECURITY_ADMIN,SUPER_ADMIN
  LOG_LEVEL: info
  PORTAL_BASE_URL: https://dev.agogos.org
